# Generated by Django 6.0.1 on 2026-01-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Firstname", models.TextField()),
                ("Lastname", models.TextField(default="")),
                ("EmailAddress", models.EmailField(max_length=254)),
                ("Phone", models.CharField()),
                ("City", models.CharField()),
                ("Country", models.CharField()),
            ],
        ),
    ]
